[package]
name = "full-app"
version = "0.1.0"
authors = ["kojiro.ueda <mxcpy608@hotmail.com>"]
edition = "2018"

[dependencies]
yew = "0.11.0"
serde = { version = "1.0", features = ["derive"] }
failure = "0.1.6"
serde_json = "1.0.48"
